In [3]:

import numpy as np

# %%
######### Exercise 1 ################
# Create a vector with 10 integer elements, all equal to 0.
a_list = [0 for i in range(10)]
print(a_list)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [9]:
arr = np.zeros(10)
print(arr, arr.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [8]:
arr = np.array(a_list)
print(arr, arr.dtype)

[0 0 0 0 0 0 0 0 0 0] int32


In [10]:
arr = np.zeros(10, dtype=np.int8)
print(arr, arr.dtype)

[0 0 0 0 0 0 0 0 0 0] int64


In [13]:
a = [1,128, 2]
np.array(a, dtype=np.int8) #tylko dla wartosci-127 do 127

C:\Users\training\AppData\Local\Temp\ipykernel_10144\4152190902.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  np.array(a, dtype=np.int8) #tylko dla wartosci-127 do 127


array([   1, -128,    2], dtype=int8)

In [14]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
print(np.ones(10, dtype=np.int8))

[1 1 1 1 1 1 1 1 1 1]


In [ ]:
######### Exercise 2 ################
# Create a vector with 10 integer elements, all equal to 1.


In [17]:
######### Exercise 3 ################
# Create a vector with integer elements from 0 to 9.
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
######### Exercise 4 ################
# Create a vector with integer elements from 10 to 29.


In [20]:
arr = np.arange(10, 30)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [21]:
arr = np.arange(9, -1, -1)
print(arr)


[9 8 7 6 5 4 3 2 1 0]


In [22]:
arr = np.random.randint(0,2,10)
print(arr)

[1 0 0 0 0 0 0 1 1 0]


In [23]:
arr = np.random.randint(0, 10, 10)
print(arr)

[9 4 8 0 8 4 7 9 5 0]


In [24]:
arr = np.random.randint(0, 100, 3)/100
print(arr)

[0.61 0.65 0.27]


In [ ]:
######### Exercise 5 ################
# Create a vector with integer elements from 0 to 9 in reverse order.


In [ ]:
######### Exercise 6 ################
# Create a vector with 10 random elements between 0 and 1.


In [ ]:
######### Exercise 7 ################
# Create a 3x3 matrix with random integer elements between 0 and 9.


In [25]:
np.random.randint(0, 10, (3,3))

array([[7, 2, 5],
       [6, 5, 8],
       [5, 3, 6]])

In [27]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
######### Exercise 8 ################
# Create a 5x5 identity matrix.


In [ ]:
######### Exercise 9 ################
# Add two matrices of equal dimensions (for example, 3x3).


In [ ]:
######### Exercise 10 ################
# Multiply two matrices of appropriate dimensions (for example, 2x3 and 3x2).


In [ ]:
######### Exercise 11 ################
# Transpose a matrix (for example, 3x4).


In [ ]:
######### Exercise 12 ################
# Find the maximum value in a vector.


In [ ]:
######### Exercise 13 ################
# Find the index of the maximum value in a vector.


In [ ]:
######### Exercise 14 ################
# Find the arithmetic mean of the values in a matrix.


In [ ]:
######### Exercise 15 ################
# Create a 4x4 matrix with random integer elements between 1 and 20.


In [ ]:
######### Exercise 16 ################
# Create a 6x6 diagonal matrix with diagonal elements equal to 5.


In [ ]:
######### Exercise 17 ################
# Reshape a vector of 12 elements into a 3x4 matrix.


In [ ]:
######### Exercise 18 ################
# Flatten a 3x4 matrix into a 1D array.


In [ ]:
######### Exercise 19 ################
# Create a vector of length 50 with linearly spaced values between 0 and 100.


In [ ]:
######### Exercise 20 ################
# Create a 5x5 matrix filled with a specific value (for example, 7).


In [ ]:
######### Exercise 21 ################
# Create a vector of 15 random integers between 50 and 100, and sort it.


In [ ]:
######### Exercise 22 ################
# Find the standard deviation of the values in a vector.


In [ ]:
######### Exercise 23 ################
# Replace all negative values in a vector with 0.


In [ ]:
######### Exercise 25 ################
# Create a random 4x4 matrix and compute the sum of all its elements.
